openapi: "3.0.0"
info:
  version: 1.0.0
  title: Interneto technologjų testo laikymo API
servers:
  - url: https://test.eyo.lt/api
paths:
  /tests:
    post:
      tags: ["tests"]
      description: "Create new test"
      requestBody:
        description: Test details
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TestToCreate'
      responses:
        '200':
          description: Test details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CeatedTest'
        '500':
          description: Internal error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalError'
  /tests/{id}:
    patch:
      tags: ["tests"]
      description: "Start test"
      parameters: 
        - name: "id"
          in: "path"
          description: "Test ID"
          required: true
          schema:
            type: string
            example: 1234
      requestBody:
        description: Test updated params
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TestToUpdate'
      responses:
        '200':
          description: List of slots
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CeatedTest'
        '400':
          description: Client error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClientError'
        '500':
          description: Internal error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InernalError'
    get:
      tags: ["tests"]
      description: "Get test details"
      parameters: 
        - name: "id"
          in: "path"
          description: "Test ID"
          required: true
          schema:
            type: string
            example: 1234
      responses:
        '200':
          description: Test details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CeatedTest'
        '400':
          description: Client error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClientError'
        '500':
          description: Internal error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InernalError'
  /tests/{testId}/students/{studentId}/questions:
    get:
      tags: ["tests students questions"]
      description: "List test questions for individual stundent"
      parameters: 
        - name: "id"
          in: "path"
          description: "Slot ID"
          required: true
          schema:
            type: string
            example: 507f191e810c19729de860ea
      responses:
        '200':
          description: Booked slot
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ReservedSlot'
        '400':
          description: Client error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClientError'
        '500':
          description: Internal error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InernalError'
  /tests/{testId}/students/{studentId}/questions/{questionId}/answers:
    post:
      tags: ["tests students questions answers"]
      description: "Submit test question answer"
      parameters: 
        - name: "id"
          in: "path"
          description: "Slot ID"
          required: true
          schema:
            type: string
            example: 507f191e810c19729de860ea
      responses:
        '200':
          description: Booked slot
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ReservedSlot'
        '400':
          description: Client error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClientError'
        '500':
          description: Internal error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InernalError'
components:
  schemas:
    TestToCreate:
      type: object
    CeatedTest:
      type: object
      properties:
        id:
          type: string
          example: 1234
        timer:
          type: number
          example: 480
        status:
          type: string
          enum: [WAITING, IN_PROGRESS, COMPLETED]
    TestToUpdate:
      type: object
      properties:
        status:
          type: string
          enum: [WAITING, IN_PROGRESS, COMPLETED]
    ClientError:
      type: object
      properties:
        message:
          type: string
          example: 'Test with ID 1234 does not exist'
    InternalError:
      type: object